### ISSUE TITLE
optical flow with superpixel

### ISSUE THREAD

**Issue by xiaofanglegoc** [NVlabs/ssn_superpixels#1]
Thank you for the release of project, and it is a great work!

In your paper, there are a section on the optical flow using SSN_{deep}, which gives a good visual results, would you please give some hints or demo on this part ?

**Comment by pinkfloyd06** [comment]
Hello,

Thank you for this work. I'm also interested on this part

**Comment by varunjampani** [comment]
I am currently on travel. I will add the sintel trained model in 'get_models.sh' script after a couple of weeks. You can use that model to obtain superpixels on sintel images using 'compute_ssn_spixels.py` script. Or, are you interested in visualization of segmented flow given the superpixels?

**Comment by xiaofanglegoc** [comment]
thanks wait for your upate

**Comment by varunjampani** [comment]
I have added 'ssn_sintel_model.caffemodel' to 'get_models.sh'. You can use this caffemodel with the 'compute_ssn_spixels.py' script to obtain superpixels on sintel images:

python compute_ssn_spixels.py  --datatype SINTEL_VAL --n_spixels 100 --num_steps 10 --caffemodel ./models/ssn_sintel_model.caffemodel --is_connected False --result_dir ./sintel_val_100/

You need to add corresponding image list and image folder locations to 'config.py'.
