### ISSUE TITLE
converge very slowly

### ISSUE THREAD

**Issue by jiayusun** [NVlabs/ssn_superpixels#13]
Hi Varun,
Super grateful for your sharing of this great work! I follow your guide, and try to train on BSDS training dataset. However, the model seems not converging after a whole day of training. I am wondering if this is because it needs a great many iterations to converge, since I find you set 'num_iter = 1000000' in train_ssn.py. 
Looking forward to your reply:)

**Comment by varunjampani** [comment]
We used 500K iterations for training. After a day of training, you should see reasonable improvements with respect to baseline SLIC model. I agree the convergence is usually slow for SSN.

**Comment by jiayusun** [comment]
Yes, I have seen the improvement. Thank you so much!
