### ISSUE TITLE
superpixel results

### ISSUE THREAD

**Issue by zicair** [NVlabs/ssn_superpixels#14]
Thank you for the release of project.

But I have a question, using pre-trained model to run directly, the result contains 'new_spix_indices' and '_bdry.jpg' in the code.  How can I get results like this:

![image](https://user-images.githubusercontent.com/41500153/57630075-86195d00-75cf-11e9-8844-33f117f9aa9a.png)

Looking forward to your reply, thank you!

**Comment by varunjampani** [comment]
Can you explain more clearly? What do you mean 'result'? Do you mean that 'visualization'?

**Comment by zicair** [comment]
I am sorry，I don't know much about superpixels. All I know about superpixels is that you get the effect where the value of each superpixel block is the average of the pixels in that area. For example，left image is raw image and right one is the visualization result. 

![image](https://user-images.githubusercontent.com/41500153/57666059-26539e00-7631-11e9-8137-b558161be906.png)

The screenshot above was taken from https://github.com/PSMM/SLIC-Superpixels

**Comment by varunjampani** [comment]
Superpixels give 'segments/clusters' (over-segmentation) of pixels an image. 'new_spix_indices' give unique number to pixels belonging to a superpixel cluster. Using those new_spix_indices, one could average the pixel values in each superpixel cluster to generate an average image.

**Comment by varunjampani** [comment]
This could be useful to learn about superpixel visualization: https://www.pyimagesearch.com/2017/06/26/labeling-superpixel-colorfulness-opencv-python/

**Comment by zicair** [comment]
I get it, thx！
