### ISSUE TITLE
caffe build configuration？

### ISSUE THREAD

**Issue by WenqiangX** [NVlabs/ssn_superpixels#15]
Can anyone provide the successful building configuration of caffe? I kept failing......

Including:
1. OS version
2. cuda version
3. cudnn version
4. protobuf version
5. python version
6. gcc version

Thanks very much!

BTW, I really do not think using caffe is a good idea these days.

**Comment by varunjampani** [comment]
Standard caffe installation should work as our new layers do not require any additional libraries: https://caffe.berkeleyvision.org/installation.html
