### ISSUE TITLE
Some confusion about training with label

### ISSUE THREAD

**Issue by forrestsz** [NVlabs/ssn_superpixels#17]
Hi, thanks for your nice work, i am very interest in it, after reading your paper, i have some point want to make sure:
in your paper, you train the snn by L=Lr+Lc right? the Lr is reconstruction loss which need the segment gt(label).
but want we using the traditional algorithm such as SLIC which don't need label right?

**so can i understand: SLIC is a unsupervised approach while SNN is a supervised(semi supervised) approach in superpixels?**

this is my question, looking forward for your reply!

**Comment by varunjampani** [comment]
Yes, we can learn task-specific superpixels with SSN, but that requires labels for that task (like semantic segmentation). One could also learn SSN superpixels with image reconstruction loss (without label reconstruction), but the improvements are not as big compared to SLIC.
