### ISSUE TITLE
Questions about semantic segmentation testing

### ISSUE THREAD

**Issue by Yajha** [NVlabs/ssn_superpixels#18]
Hi, thank you for your excellent work. I have a little confusion about your paper.
In your paper, you mention that the ssn can be used for downstream tasks. Here's my question
in semtantic segmentaion, you need to use GT of pixel label to get superpixels, but how to get pixel label in testing, or here semantic segmentation is just a form to help ssn get superpixels?

I wish to get your reply.Thank you.

**Comment by varunjampani** [comment]
We do not need GT semantic labels during testing. Yes, semantic segmentations labels are used during training to learn superpixels that are more suitable for semantic segmentation (if one wants to use it for semantic segmentation). Similarly for optical flow as well: Superpixels trained with optical flow can better represent optical flow. One could use superpixels trained for semantic segmentation for other tasks as well if they are found to be useful.

**Comment by Yajha** [comment]
Thank you for your prompt reply.
