### ISSUE TITLE
some question of paper about training

### ISSUE THREAD

**Issue by yuzhegao** [NVlabs/ssn_superpixels#20]
Hi!  
Thanks for sharing this nice work, but I still have some question about this paper. 

As mentioned in paper,  before the SSN module, the image is feed to a CNN and then get k-dimension pixel features. i.e the tensor of n × k.  and then this pixel features was cluster and get m super-pixel representation of k-dimension (m × k),  and finally we should map the super-pixel representation(m × k) back to pixel representation(n × k)  using matrix multiply, to compute the pixel-wise loss. Is my interpretation correct ? 

In Section 4.3, we should compute  Task-specific reconstruction loss using pixel properties(label) R  and  pixel representation R∗,  so here the R∗ is pixel representation(n × k) which is from super-pixel representation mentioned above. Is that right ?

**Comment by SadSock** [comment]
n your paper “Superpixel Sampling Networks”，I was confused by the loss function:
<img width="616" alt="图片" src="https://user-images.githubusercontent.com/7643216/64905935-b30e8580-d711-11e9-8cff-9911cbf7abe2.png">
which symbol denote the output of the SSN?

**Comment by varunjampani** [comment]
Q is the output of the network, which gives soft-mapping from pixels to superpixels. Q is of size Nx9 in this work, where N is number of pixels and 9 denotes the number of surrounding 3x3 superpixels. R can be any pixel representation that we want superpixels to preserve. R can be pixel RGB values, semantic segmentation, optical flow or some other pixel features.

**Comment by yuzhegao** [comment]
@varunjampani  Thanks for your answer ! one more question. Does this SSN_network only predict the super-pixel in image, but not predict result of specific task like segmentation or optical flow?

**Comment by varunjampani** [comment]
SSN network only predicts superpixels that are tuned to represent representations (such as segmentation, optical flow etc.). SSN does not predict results for those tasks.
