### ISSUE TITLE
Some question about initialization of group conv layer 'concat_spixel_feat_50' 

### ISSUE THREAD

**Issue by yuzhegao** [NVlabs/ssn_superpixels#24]
Hi! @varunjampani
Sorry to bother you again.  When I want to use ssn as a module, I meet some problem: There is a group conv layer 'concat_spixel_feat_50'  in function "def decode_features" (in file 'create_net.py') which is used to Concatenate neighboring 9 superpixel feature, is that right? 
When I visualize the params of this layer in the pretrained-model, I get conv-params like this:
(which is correct initialize, for concat neighboring 9 feature)
![image](https://user-images.githubusercontent.com/35888464/67014611-b5f10180-f127-11e9-90d9-59129e2a960c.png)
However, after I add the same code to my own network, I get the all-zero init of this layer 'concat_spixel_feat_50' 
![image](https://user-images.githubusercontent.com/35888464/67014685-d751ed80-f127-11e9-86a3-410481473e1d.png)
I have checked the document of caffe: when the param "weight_filler" is not set,  then the kernel param of this conv layer will  initial with all-zero. Obviously the all-zero init  is not correct, but I can't get the correct params initialization above. I use the same code and really can't find which setting is wrong.
Could you please give some help? Thanks a lot !

**Comment by yuzhegao** [comment]
I guess I have found the problem .... I forgot the weight initial function, Thanks !

**Comment by yuzhegao** [comment]
I guess I have found the problem .... I forgot the weight initial function, Thanks !

**Comment by varunjampani** [comment]
Yes, I think, its 'initialize_net_weight' in utils.
