### ISSUE TITLE
about Evaluation

### ISSUE THREAD

**Issue by lokiii6** [NVlabs/ssn_superpixels#25]
On the BSDS dataset, I used the parameters provided（ssn_bsds_model.caffemodel)to get better result for ASA and BR than the paper. May I ask if the parameters provided are the parameters used in the paper

**Comment by varunjampani** [comment]
I think the released parameters are the ones used in the paper. Did you use the same evaluation settings (e.g. boundary tolerance for BR score) as in the paper?
