### ISSUE TITLE
The implementation of pytorch version

### ISSUE THREAD

**Issue by CYang0515** [NVlabs/ssn_superpixels#28]
Recently, I work on a pytorch implementation of your paper. Some implementation results are shown as follows:
![image](https://user-images.githubusercontent.com/45357137/69630222-bfa34880-1087-11ea-9dff-c23f96305736.png)
![image](https://user-images.githubusercontent.com/45357137/69630494-f5e0c800-1087-11ea-8a93-b4210f55d6c9.png)
There is one straight line at close to the image boundary, and I do not konw why. In your experiments, is there the simiar problem? And can you give me some advices?
Another problem is that the pos_recon loss will decrease at the begining of training and gradually increase with a long training period.

**Comment by varunjampani** [comment]
It seems something wrong with the border superpixels. They seem to be not updating properly. Can you check if the neighborhood superpixels for border pixels are correct? You can also try experimenting with different superpixel initializations to debug the issue.

It would be great if you can share the pytorch implementation to the community once it is ready. Thanks.

**Comment by Zhaoyi-Yan** [comment]
@CYang0515 Hi, is the implementation ready ? It's useful in my current work. Thank you!

**Comment by CYang0515** [comment]
yes,&nbsp; I will release the code recently.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zhaoyi-Yan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月1日(星期三) 下午4:54
收件人:&nbsp;"NVlabs/ssn_superpixels"<ssn_superpixels@noreply.github.com&gt;;
抄送:&nbsp;"Fleet_Time"<454232091@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [NVlabs/ssn_superpixels] The implementation of pytorch version (#28)




@CYang0515 Hi, is the implementation ready ? It's useful in my current work. Thank you!

**Comment by Zhaoyi-Yan** [comment]
@CYang0515 Please let me be informed  ASAP if the code is released.

**Comment by CYang0515** [comment]
@Zhaoyi-Yan The code has released in https://github.com/CYang0515/pytorch_ssn.git.

**Comment by varunjampani** [comment]
Thanks for sharing the pytorch implementation.

**Comment by PkuRainBow** [comment]
@CYang0515 Nice work, we are wondering whether have you address the mentioned issues.
