### ISSUE TITLE
I cannot understand “n*9” mentioned in the paper

### ISSUE THREAD

**Issue by TakeruIto** [NVlabs/ssn_superpixels#29]
Hi.
I try to implement this in pytorch. But I cannot understand how to calculate Q.

The paper says
“we constrain the distance computations from each pixel to only 9 surrounding superpixels”
This confuses me.

1. Is there any chance that more than or less than 9 superpixel centers are in the red box?

2. When the size of Q is n x 9 and I is n x k(k is feature dim), QI is 9 x k, right? If so, how can I get the m x k size superpixel centers?

I apologize for my poor English and thank you for your help.

**Comment by varunjampani** [comment]
The questions are not that clear to me.

For 1: For each pixel in green box, we compute distances to the 9 superpixels that are initialized in the red box. 

For 2: What do you mean QI? Conceptually, Q is nxm matrix. Practically, we compute only nx9 elements in that matrix, for efficiency.
