### ISSUE TITLE
Question About your paper

### ISSUE THREAD

**Issue by lxtGH** [NVlabs/ssn_superpixels#3]
when you comput Q Algorithm 1 in your paper, did you use the normalization technique?  because the Q seems to be very small.

**Comment by varunjampani** [comment]
Yes, we normalize Q for computing the updated superpixel centroids (Line-5 in Algo-1). Basically, this is a softmax operation (see lines 84-97 in create_net.py). Is this clear?

**Comment by lxtGH** [comment]
Thanks for reply,  how do you choose the number of iteration? why you choose 5? I found the more iteration, the less discriminative of the centroids of each pixel when searching all pixels for calculating the superpixel centroids. @varunjampani

**Comment by varunjampani** [comment]
The validation performance usually increases with the number of iterations, both in SLIC and in our modified differentiable SLIC. We choose 5 iterations to make training faster which takes several days. And, we choose 10 iterations for testing as we observe only marginal improvements with more iterations. I could not clearly understand what you mean by 'discriminative of the centroids of each pixel'. Can you explain more clearly what you mean by that?
