### ISSUE TITLE
Why is random cropping / patching and random scaling applied continuously throughout training?

### ISSUE THREAD

**Issue by ghost** [NVlabs/ssn_superpixels#31]
Hello,

According to the paper, random patches and random scaling of those patches are used as a means of data augmentation. My question is why are these forms of data augmentation applied continuously throughout the training process i.e. when the data is loaded during the training process.

Wouldn't it be enough to augment the BSDS500 data before training, and then running training on a fixed, yet augmented dataset (especially since there are multiple annotations for each image in the BSDS500 dataset)? It appears that applying data augmentation continuously throughout training may be the reason it takes so long to train SSN (~500K iterations).

Thank you in advance :)

**Comment by varunjampani** [comment]
Yes, one could also pre-store the augmented data to make the training faster. Depending on the size of the resulting dataset, the performance may be similar to doing cropping on-the-fly.
