### ISSUE TITLE
Superpixel border issue on BSDS500 dataset

### ISSUE THREAD

**Issue by yuanqqq** [NVlabs/ssn_superpixels#35]
Hi, I'm trying to test your algorithm on BSDS500 dataset. I follow your instruction in README.md and run compute_ssn_spixels.py using your args. However, I get abnormal results like this.
![36046_bdry](https://user-images.githubusercontent.com/35369804/102965628-329c1e80-4529-11eb-8597-df259e43ad6f.jpg)
It can not assign correct superpixel ID for the boundary of images.
Did you encounter this problem? Or do you know the reason?

**Comment by varunjampani** [comment]
Seems something is wrong at the borders. Might be coming due to some numerical issues at the borders? Please check the pixel-superpixel association values at the borders. There is a pytorch implementation by someone else which you may want to try as well: https://github.com/CYang0515/pytorch_ssn

**Comment by yuanqqq** [comment]
Pixel-superpixel association values at the borders are equal at some dimensions as following:
![Screenshot from 2020-12-23 22-28-27](https://user-images.githubusercontent.com/35369804/103007408-55045b00-456e-11eb-99c2-80390fd4a549.png)
![Screenshot from 2020-12-23 22-29-09](https://user-images.githubusercontent.com/35369804/103007411-57ff4b80-456e-11eb-8e35-7c5572896d54.png)
I have tried the pytorch implementation, it works and this problem does not occur.

**Comment by varunjampani** [comment]
Corner pixels do not have all the 9 neighboring superpixels to compute associations. I explicitly dealt with this in the code with 'invalid_spixel' flag in the code: https://github.com/NVlabs/ssn_superpixels/blob/master/lib/src/caffe/layers/passoc_layer.cu
For instance, the [0,0] pixel has only 4 valid superpixels for which it associates to. Not sure why 5 superpixels have non-zero values at [0,0].

Several people have reproduced the results using this repo. So, I don't think there is a bug for this. Check if the superpixel initialization is correct. That is computed by 'get_spixel_init' in https://github.com/NVlabs/ssn_superpixels/blob/master/utils.py

**Comment by yuanqqq** [comment]
I have found the reason. I made a ridiculous mistake. When I download your trained model, I didn't notice there was something wrong with network connection. So I test with a empty model file. Thanks for your prompt reply.

**Comment by varunjampani** [comment]
Great. Good to know that.
