### ISSUE TITLE
when i run your code using pycharm,the error is..

### ISSUE THREAD

**Issue by farm365** [NVlabs/ssn_superpixels#5]
**Error parsing text-format caffe.NetParameter: 23:23: Message type "caffe.LayerParameter" has no field named "pixel_feature_param".**
In the caffe.proto file,the variable is existed.
 I install caffe in the ringht way,but always arised that worng,please help me! Thank you very much!

**Comment by varunjampani** [comment]
Did you follow instructions and installed caffe from 'Video Propagation Networks' (https://github.com/varunjampani/video_prop_networks) ? 'PixelFeature' layer is from that repository.

**Comment by farm365** [comment]
thank you !I believe your work is very important,i will install caffe again!
