### ISSUE TITLE
Test for city_scapes dataset?

### ISSUE THREAD

**Issue by Wanger-SJTU** [NVlabs/ssn_superpixels#7]
Error while test on city_scapes dataset?
> F1128 11:33:33.655436 27257 blob.cpp:34] Check failed: shape[i] <= 0x7fffffff / count_ (2048 vs. 1182) blob size exceeds INT_MAX
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by varunjampani** [comment]
As mentioned in Section 5.2, we experiment with half-resolution images (512x1024) on Cityscapes. There seem to be a INT_MAX issue when dealing with full-resolution images.

**Comment by Wanger-SJTU** [comment]
thx
