### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Eileen2014** [NVlabs/ssn_superpixels#8]
http://www.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/BSR/BSR_full.tgz > BSDS.tgz
can not open this network
please give another network or cloud storage

**Comment by varunjampani** [comment]
The link seems to be working now. You can also access the same data file here: https://www.dropbox.com/s/ox6aozbojst0lmx/BSR_full.tgz?dl=0
